---
title: "Data Manipulation"
output: html_document
---

```{r setup}
library(tidyverse)
```

## Load in the FAS Litters Data 

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

## 'Select'

Choose some columns and not others.

```{r}
select(litters_df, group, litter_number)

select(litters_df, group, gd0_weight)

select(litters_df, group, gd0_weight:gd_of_birth)
```

```{r}
select(litters_df, -litter_number)
```

Renaming columns... 

```{r}
select(litters_df, GROUP = group)
```

```{r}
select(litters_df, LITLLE_number = litter_number)

```

Select helpers 

```{r}
select(litters_df, starts_with("gd"))

```


```{r}
select(litters_df, litter_number, everything())
```


```{r}
relocate(litters_df, litter_number)
```


## `filer`

```{r}
filter(litters_df, gd0_weight<22)
```

```{r}
filter(litters_df, gd0_weight >= 22)
```

```{r}
filter(litters_df, gd_of_birth == 20)
```

```{r}
filter(litters_df, !gd_of_birth == 20)
```

```{r}
filter(litters_df, gd0_weight >= 22, gd_of_birth == 20)
```

```{r}
filter(litters_df, group == "Mod8")
filter(litters_df, group == "Con7")
```

```{r}
filter(litters_df, group%in% c("Con7", "Mod8"))
```
